name: Generate Summary

on:
  pull_request:
    types: [closed]

jobs:
  generate_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Generate summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 generate_summary.py --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }} --branch ${{ github.ref }} --pr ${{ github.event.pull_request.number }}
